matched all backgrounds
jcmugabi/web-project-1 pull request #7
Opened 2022-12-11 20:09 UTC by jcmugabi

- [x] 'Gallery' and 'about-us' backgrounds differed from the rest. Matched them.

2022-12-13 13:19 UTC, kusaasira requested changes

2022-12-13 13:19 UTC, kusaasira commented on Gallery.html
> +            <li><a href=".\AboutUs-2.html">About Us</a></li>
This needs to be updated.

2022-12-13 13:20 UTC, kusaasira requested changes
Update the about us page link (href) on the gallery page to point to the right page,

2022-12-15 14:43 UTC, jcmugabi commented on Gallery.html
> +            <li><a href=".\AboutUs-2.html">About Us</a></li>
- [x] Updated.

2022-12-15 14:43 UTC, kusaasira approved these changes

2022-12-15 14:43 UTC, merged